### ISSUE TITLE
Uncaught TypeError: Cannot read property 'postMessage' of null

### ISSUE THREAD

**Issue by letoss** [eventioz/gcontacts#6] opened 2015-01-27 16:59 UTC
This is happening because the opener is not defined. In my case I've defined the window.parent. So, I should changed the source code to parent to use it.

Is there a way to do that opener works everytime?

**Comment by gagoar** [comment] 2015-01-27 17:48
the `postMessage` exist as a "secure" way of connect the window hosting the Google  authorization (not controlled by us) and out initial webpage, could you share the changes that you have made in order to understand better, why is falling? 

Offhand I can tell you that would be possible to give as an option this parent element where we should look for the parent element to search for the postMessage function. But I would like more information.

**Comment by gagoar** [comment] 2015-03-13 01:24
given that @letoss haven't answered and I can't reproduce the issue. I'm closing this issue.

**Closed by gagoar** 2015-03-13 01:24 UTC
Labels: enhancement
